pipeline {
    agent any

    environment {
        FRONTEND_IMAGE = "eventfrontend.azurecr.io/event-frontend:latest"
        BACKEND_IMAGE = "eventbackendacr.azurecr.io/event-backend:latest"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'eventtest', url: 'https://github.com/bercoding/EventTicketPortal.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    bat "docker build -t eventticketportal-frontend:latest -f frontend/Dockerfile ."
                    bat "docker build -t eventticketportal-backend:latest -f backend/Dockerfile ."
                }
            }
        }

        stage('Login to ACR') {
            steps {
                script {
                    bat "az acr login --name eventfrontend"
                    bat "az acr login --name eventbackendacr"
                }
            }
        }

        stage('Tag and Push to ACR') {
            steps {
                script {
                    bat "docker tag eventticketportal-frontend:latest %FRONTEND_IMAGE%"
                    bat "docker push %FRONTEND_IMAGE%"

                    bat "docker tag eventticketportal-backend:latest %BACKEND_IMAGE%"
                    bat "docker push %BACKEND_IMAGE%"
                }
            }
        }
    }
}
